name: logarte
description: Graphical Debug Console for Flutter
version: 0.1.3
repository: https://github.com/kamranbekirovyz/logarte

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.4.1
  flutter:
    sdk: flutter
  stack_trace: ^1.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: